# Generated by Django 4.2.3 on 2023-09-16 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppPerfil', '0004_userinventory_remove_profile_id_carta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinventory',
            name='user',
            field=models.CharField(max_length=100),
        ),
    ]
