# Generated by Django 4.2.3 on 2023-09-18 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppPerfil', '0005_alter_userinventory_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinventory',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='games',
            field=models.IntegerField(default=0),
        ),
    ]
