# Generated by Django 4.2.3 on 2023-09-20 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppPerfil', '0006_userinventory_quantity_alter_profile_games'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinventory',
            name='coleccion',
            field=models.CharField(default='None', max_length=20),
        ),
    ]
