# Generated by Django 4.2.3 on 2023-09-20 01:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppPerfil', '0007_userinventory_coleccion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinventory',
            old_name='coleccion',
            new_name='type',
        ),
    ]
