# Generated by Django 4.2.3 on 2023-09-25 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppPerfil', '0008_rename_coleccion_userinventory_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='days',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
