version: '3.8'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    command: 'python manage.py runserver 0.0.0.0:8004'
    ports:
      - 8004:8004
    volumes:
      - .:/app
  
  queue:
    build:
      context: .
      dockerfile: Dockerfile
    command: 'python consumer2.py'
    networks:
      - mynetwork

networks:
  mynetwork:


